### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/design-system#14]
icons

- custom icons
- [react-icons](https://react-icons.github.io/react-icons/icons?name=fa)?
- [consolidate with current icons](https://raid-guild.github.io/design-system/?path=/story/components-atoms-icons--icon-lib)

**Comment by ChialiTsai** [comment]
drop a set of custom icons made by Richard Schumann -https://www.figma.com/community/file/986322091716622056/fusion---Free-Iconset

merge RG custom illustration icons to figma


Agree to use https://react-icons.github.io/react-icons/icons?name=fa for any additional ones

**Comment by scottrepreneur** [comment]
Moving the fusion icons to its own issue #36
