### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/design-system#16]
switch/toggle

<img width="441" alt="Screen Shot 2022-02-04 at 5 20 39 PM" src="https://user-images.githubusercontent.com/1778380/152616923-481f0b1d-9f9e-4fdd-8140-1db992fd5e9a.png">

Form Control? Uncontrolled?

**Comment by ChialiTsai** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/16527634/153780635-e455888f-491a-4914-afe1-f477e26826e9.png">
