### ISSUE TITLE
textarea not consistent

### ISSUE THREAD

**Issue by 0xhanvalen** [raid-guild/design-system#55]
![image](https://user-images.githubusercontent.com/103603290/208568255-50c43efa-b4a0-4b69-a65e-48d6b39016e8.png)
 Looks like the background for text areas is `transparent,` should be themed.

Observe: Textarea rg styling doesn't define a background property 
![image](https://user-images.githubusercontent.com/103603290/208568351-2f787619-9993-4668-b797-c8ff5e5fc20f.png)

while the Input element does
![image](https://user-images.githubusercontent.com/103603290/208568403-6c0ccd94-53be-400f-895c-ddd9132c9a10.png)

Pls fix :3 <3

**Comment by jonathanprozzi** [comment]
Ahh! I'll add this support when working on the other linked issue 🤙 thanks for the detail

**Comment by jonathanprozzi** [comment]
@0xhanvalen Fixing this now -- quick question about the usage in the example. Are you using this in an app that supports light and dark mode?

**Comment by jonathanprozzi** [comment]
This'll be fixed in the PR that includes the Input and Textarea additions. #57

**Comment by 0xhanvalen** [comment]
@jonathanprozzi it shouldn't matter if it's light or dark mode I don't think

**Comment by jonathanprozzi** [comment]
> @jonathanprozzi it shouldn't matter if it's light or dark mode I don't think

For sure -- only reason I was asking is because the tokens for the textarea take an array for the bg color for the modes. It's one of the only ones that does this. 

Will be fixed as soon as we publish the new changes and merge in #68
