### ISSUE TITLE
controlled inputs

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/design-system#57]
we have react-hook-form versions of the inputs. add controlled versions for times when a controlled input is needed

v1
- [x] Input
- [x] Textarea
- [ ] Select

Could punt to next task:
- [ ] NumberInput
- [ ] Checkbox
- [ ] Radio Button
- [ ] Error Messages (strategy + pattern, adding to all input atoms)

**Comment by scottrepreneur** [comment]
If you do Textarea plz look at #55 bg styles 🙏

**Comment by jonathanprozzi** [comment]
Working on these and realized we'd want to add the error state handling via the FormError likely -- this is something we also probably want to add to the other Inputs that are already in the system. Thoughts @scottrepreneur ?

**Comment by jonathanprozzi** [comment]
> If you do `Textarea` plz look at #55 bg styles 🙏

Fixed as part of this PR. Going to put one up for the Input + Textarea, and a separate one for the Selects since we'll add support for react-select or the Chakra wrapped version.
