### ISSUE TITLE
select updates

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/design-system#60]
- add `chakra-react-select` wrapper
- default styling is pretty good. add gradient outline/variants?

**Comment by jonathanprozzi** [comment]
Versions that will be useful:
- Controlled / Uncontrolled with prop to set multi
- Creatable -- this may make sense to be a prop, but also may want to be its own component since it behaves differently (react-select)

**Comment by jonathanprozzi** [comment]
This'll be closed by #78
