### ISSUE TITLE
Info stack

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/design-system#69]
Displays some data below a heading from [Dungeon Master](https://github.com/raid-guild/dungeon-master-v2/blob/develop/apps/frontend/components/InfoStack.tsx)

Optimize this a bit

- Pass prop for handleCopy
- Include copy icon to right on value text
- pass in value text
- all additional prop for copyText that can be used instead of the value

**Comment by kon-rad** [comment]
Closed as requires 'next' package in design-system, was decided not to do extract InfoStack from dm at this time, because it's not sufficiently general of a component.
