### ISSUE TITLE
TSDX lint is broken

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/design-system#90]
Creating an issue to fix this in the future if possible. 

`yarn lint` keeps returning 

```bash
Error: Cannot read config file: /Users/ken/dev/design-system/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: BaseConfig
    at Object.<anonymous> (/Users/ken/dev/design-system/node_modules/eslint-config-prettier/@typescript-eslint.js:1:7)
 ```

After some trial-and-error this appears to be and issue with tsdx using an older eslint config:
- https://github.com/jaredpalmer/tsdx/issues/1077

Ther developer states this it's diffifult to workaround, so configuring eslint in the yarn script is the quickes workaround.

Hotfix in #38

**Comment by scottrepreneur** [comment]
fixed
